#!/bin/bash -l
#OAR -n energy
#OAR -t moonshot
#OAR -l nodes=2,walltime=2

export DIR_NAME="moonshots_2_node"
export NB_TESTS="15"

module load mpi/OpenMPI/1.6.4-GCC-4.7.2
module use $PROJECTWORK/project_pwrmon/soft/modules
module load likwid

mkdir ${DIR_NAME}

mpiCC MPI_FinalProject.cpp -o MPI_FinalProject -pthread -std=gnu++0x -D_GLIBCXX_USE_NAN$ -D_GLIBCXX_USE_NANOSLEEP

cp MPI_FinalProject ./${DIR_NAME}/MPI_FinalProject

cd $DIR_NAME

likwid-powermeter -i &> CPU_info_host_${HOSTNAME}.log

sort -u $OAR_NODEFILE >> hosts

mpirun -hostfile ./hosts likwid-powermeter ./MPI_FinalProject &>  ${HOSTNAME}_tests_ever_mesure.log
wait $!
rm -rf testLog_*

mpirun -hostfile ./hosts likwid-perfctr -C S0 -g ENERGY -t 500ms ./MPI_FinalProject &>  ${HOSTNAME}_energ.log
wait $!
for i in `seq 1 ${NB_TESTS}`; do
    mpirun -hostfile ./hosts likwid-powermeter ./MPI_FinalProject $i &>  ${HOSTNAME}_test_$i
    wait $!
done

rm MPI_FinalProject
